name: new_todo_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^1.0.7
  animated_text_kit: ^4.2.0
  firebase_core: ^1.1.0
  provider: ^5.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/

  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono.ttf
        - asset: fonts/RobotoMono-Italic.ttf
          style: italic
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf

  uses-material-design: true


